# Generated by Django 5.1.6 on 2025-03-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipe_author_recipe_createdon_recipe_updatedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
