# Generated by Django 5.1.6 on 2025-05-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='image',
            new_name='file',
        ),
    ]
